;P2.0 - P2.7 conectados a los pines DO - D7 de la pantalla
		;P0.0 RS
		;P0.1 RW
		;P0.2 E
		
	ORG 0H
	MOV A, #38H	;USA DOS LINEAS UNA MATRIZ DE 5X7
	CALL COMM
	CALL DELAY

	MOV A, #0FH	;LCD ENCENDIDO, CURSOR ENCENDIDO, PARPADEO ENCENDIDO
	CALL COMM
	CALL DELAY

	MOV A,#06H	;INCREMENTAR POSICION DEL CURSOR
	CALL COMM
	CALL DELAY

	MOV A, #01H	; LIMPIAR PANTALLA Y RETORNAR EL CURSOR
	CALL COMM
	CALL DELAY	
	;----------------------------------------- FIN DE INICIALIZACIÓN --------------------------------

	MOV A, #'J'
	CALL ESCRIBIR
	CALL DELAY

	MOV A, #'O'
	CALL ESCRIBIR
	CALL DELAY

	MOV A, #'N'
	CALL ESCRIBIR
	CALL DELAY

	MOV A, #'A'
	CALL ESCRIBIR
	CALL DELAY

	MOV A, #'T'
	CALL ESCRIBIR
	CALL DELAY

	MOV A, #'H'
	CALL ESCRIBIR
	CALL DELAY

	MOV A, #'A'
	CALL ESCRIBIR
	CALL DELAY

	MOV A, #'N'
	CALL ESCRIBIR
	CALL DELAY

	MOV A, #11000001B ;COMANDO LINA 2 EN LA POSICION 1
	CALL COMM
	CALL DELAY

	MOV A, #'D'
	CALL ESCRIBIR
	CALL DELAY

	MOV A, #'I'
	CALL ESCRIBIR
	CALL DELAY

	MOV A, #'E'
	CALL ESCRIBIR
	CALL DELAY

	MOV A, #'G'
	CALL ESCRIBIR
	CALL DELAY

	MOV A, #'O'
	CALL ESCRIBIR
	CALL DELAY

LOOP:	SJMP LOOP	;SE MANTIENE AQUÍ MOSTRANDO EL NOMBRE
	
	;-----------------------------FUNCIONES--------------------
	COMM:
	MOV P2, A	;COPIA LO QUE HAY EN A EN P1
	CLR P0.0	;RS = 0 PARA COMANDO
	CLR P0.1	;RW = 0 PARA ESCRIBIR
	SETB P0.2	; E = 1 PULSO ALTO
	CALL DELAY
	CLR P0.2	; E = 0 PULSO BAJO
	RET

	ESCRIBIR:
	MOV P2, A	;COPIA LO DE A A P1
	SETB P0.0	;RS = 1 PARA DATOS
	CLR P0.1	;RW = 0 PARA ESCRIBIR
	SETB P0.2	; E = 1 PARA ENVIAR PULSO ALTO
	CALL DELAY
	CLR P0.2	;E = 0 PARA PULSO BAJO
	RET

	DELAY:
	MOV R3, #50	;R3 = 50
AQUI2:	MOV R4, #50	;R4 = 255
AQUI:	DJNZ R4, AQUI	;QUEDA AQUÍ HASTA QUE R4 SE VUELVA 0
	DJNZ R3, AQUI2	;SE REPITE EL CICLO HASTA QUE R3 ES 0
	RET
	END
